#!/bin/sh
# autopkgtest check for simage
# (C) 2016 Anton Gladky <gladk@debian.org>

set -e

WORKDIR=$(mktemp -d)
trap "rm -rf $WORKDIR" 0 INT QUIT ABRT PIPE TERM
cp debian/tests/a_in.png $WORKDIR/ 
cp examples/simage-read-line-test.c $WORKDIR/ 

cd $WORKDIR

gcc simage-read-line-test.c -lsimage -o simage-read-line-test
echo "build: OK"

./simage-read-line-test a_in.png a_out.png
ls -ln

echo "run: OK"
